Parameters:
  ProjectPrefix:
    Type: String
Resources:
  CloudFormationRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub ${ProjectPrefix}-CloudFormationRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "cloudformation.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        -
          PolicyName: "CloudFormationPolicy1"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "ec2:RevokeSecurityGroupIngress"
                  - "ec2:AuthorizeSecurityGroupEgress"
                  - "ec2:AuthorizeSecurityGroupIngress"
                  - "ec2:UpdateSecurityGroupRuleDescriptionsEgress"
                  - "ec2:CreateSecurityGroup"
                  - "ec2:RevokeSecurityGroupEgress"
                  - "ec2:DeleteSecurityGroup"
                  - "ec2:UpdateSecurityGroupRuleDescriptionsIngress"
                Resource:
                  - !Sub "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:vpc/{{resolve:ssm:${ProjectPrefix}-vpcid:1}}"
                  - !Sub "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:security-group/*"
              -
                Effect: "Allow"
                Action:
                  - "ec2:DescribeSecurityGroups"
                Resource:
                  - "*"  
              -
                Effect: "Allow"
                Action:
                  - "ssm:GetParameters"
                Resource:
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ProjectPrefix}-vpcid"
              -
                Effect: "Allow"
                Action:
                  - "s3:GetObject"
                Resource:
                  - !Sub "arn:aws:s3:::release-bucket-${ProjectPrefix}-${AWS::Region}-${AWS::AccountId}/*"
Outputs:
  CloudFormationRoleArn:
    Value: !GetAtt CloudFormationRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-CloudFormationRoleArn"
  StackName:
    Value: !Ref AWS::StackName 
